### ISSUE TITLE
FileNotFoundError when testing Diablo_ACMG

### ISSUE THREAD

**Issue by Giuseppe1995** [TheSergeyPixel/Diablo_ACMG#1]
Hi, I am trying to use your software for annotating variants according to ACMG criteria. I installed all the modules (apparently in the repo directory) and also the oc modules as described in the manual. When I tried to run the example I was given the following error:

`python Diablo_annotate.py -i test/IDTEPF.vcf.gz -o test/test.tsv`

> Invalid module: tsvreporter
> Loading dataframe...
> Traceback (most recent call last):
>   File "/srv/ngs/analysis/dalteriog/Tools/Diablo_ACMG/Diablo_annotate.py", line 56, in <module>
>     df = pd.read_csv(
>          ^^^^^^^^^^^^
>   File "/srv/ngsdata/dalteriog/Tools/miniconda3/envs/diablo_acmg/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
>     return _read(filepath_or_buffer, kwds)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/srv/ngsdata/dalteriog/Tools/miniconda3/envs/diablo_acmg/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 577, in _read
>     parser = TextFileReader(filepath_or_buffer, **kwds)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/srv/ngsdata/dalteriog/Tools/miniconda3/envs/diablo_acmg/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
>     self._engine = self._make_engine(f, self.engine)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/srv/ngsdata/dalteriog/Tools/miniconda3/envs/diablo_acmg/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
>     self.handles = get_handle(
>                    ^^^^^^^^^^^
>   File "/srv/ngsdata/dalteriog/Tools/miniconda3/envs/diablo_acmg/lib/python3.11/site-packages/pandas/io/common.py", line 859, in get_handle
>     handle = open(
>              ^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: '/srv/ngs/analysis/dalteriog/Tools/Diablo_ACMG/test/IDTEPF.variant.tsv'
> 

Thank you in advance, 
Giuseppe

**Comment by TheSergeyPixel** [comment]
Hey! Thanks for reaching out. I believe, that this error can be overcome with the following line of code prior to executing the software:

```
oc module install tsvreporter
```

Let me know if it fixes the error.

**Comment by Giuseppe1995** [comment]
Yes! thank you so much!
